version: '2'
services: 
  rabbitmq:
    image: rabbitmq:3-management

  mongo:
    image: mongo:3.2
  
  core:
    image: fpommerening/spartakiade2017-rabbitmq:core-base

  imagedb:
    image: fpommerening/spartakiade2017-rabbitmq:picflow-database
    
  web:
    depends_on:
      - rabbitmq
      - mongo
      - imagedb
    image: fpommerening/spartakiade2017-rabbitmq:StartupApp
    ports:
      - 18317:18317