version: '2'
services: 
  rabbitmq:
    image: rabbitmq:3-management

  mongo:
    image: mongo:3.2
  
  core:
    image: fpommerening/spartakiade2017-rabbitmq:core-base
    
  web:
    depends_on:
      - rabbitmq
      - mongo
    image: fpommerening/spartakiade2017-rabbitmq:StartUpApp
    ports:
      - 18317:18317